name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.24

    steps:
      - uses: actions/checkout@v4

      - name: Build the project
        run: make build

      - name: Run unit tests
        run: make test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
